// <auto-generated />
using System;
using MarketDataApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketDataApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326192456_SeedAssets")]
    partial class SeedAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketDataApi.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("019cfb9b-5d5b-73a3-a2e8-5c537ee593cd"),
                            Kind = "forex",
                            Symbol = "EURUSD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5be1-73e9-9797-8eac7cda5349"),
                            Kind = "forex",
                            Symbol = "GBPUSD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5c16-7217-8108-2a1dfe834b90"),
                            Kind = "forex",
                            Symbol = "USDJPY"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5c79-7f09-993b-8e0e996f58fe"),
                            Kind = "forex",
                            Symbol = "USDCHF"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5e7a-7199-b906-93f3e818bf62"),
                            Kind = "forex",
                            Symbol = "USDCAD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5c36-7326-b890-d37568bd3637"),
                            Kind = "forex",
                            Symbol = "AUDUSD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5c0c-7356-8f75-f627cd37f302"),
                            Kind = "forex",
                            Symbol = "AUDNZD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5da5-76fc-b6c0-1b9c270040c3"),
                            Kind = "forex",
                            Symbol = "AUDJPY"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5ccd-7064-bb8c-4aa47a93c6f1"),
                            Kind = "forex",
                            Symbol = "EURAUD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5bbd-7bf6-975a-19a538210610"),
                            Kind = "forex",
                            Symbol = "EURCAD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5d23-7009-9ced-057bc85fbdf3"),
                            Kind = "forex",
                            Symbol = "EURCHF"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5c6f-7eac-b85c-0c9dd8a09e4b"),
                            Kind = "forex",
                            Symbol = "EURGBP"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5d82-75a9-9df4-fde04e4fd481"),
                            Kind = "forex",
                            Symbol = "EURJPY"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5e3d-7dc8-b4c3-fa4cc90997ba"),
                            Kind = "forex",
                            Symbol = "EURNZD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5d0c-7111-9df6-fa14c5f4c87d"),
                            Kind = "forex",
                            Symbol = "GBPJPY"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5dbb-7cc9-ba07-0ddb62828135"),
                            Kind = "forex",
                            Symbol = "GBPCHF"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5c57-7a5e-bed8-f0e7a7558526"),
                            Kind = "forex",
                            Symbol = "NZDUSD"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-6035-7777-8217-f936ffaed040"),
                            Kind = "forex",
                            Symbol = "NZDCHF"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5ec6-7a27-b223-fa0c0f5b13c6"),
                            Kind = "forex",
                            Symbol = "USDSEK"
                        },
                        new
                        {
                            Id = new Guid("019cfb9b-5c41-7907-b0d7-1eb0dd665012"),
                            Kind = "forex",
                            Symbol = "USDPLN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
